# Generated by Django 5.2.7 on 2025-11-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('check', 'Check')], default='cash', max_length=20),
        ),
    ]
