# Generated by Django 5.2.7 on 2025-11-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='refund_payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('check', 'Check')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
