# Generated by Django 5.2.7 on 2025-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_discount_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, help_text='Receipt label/SKU for this product', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='receipt_label',
            field=models.CharField(blank=True, help_text='Custom label for receipt', max_length=255),
        ),
    ]
