# Generated by Django 4.2.7 on 2025-12-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_add_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='transaction_date',
            field=models.DateField(blank=True, help_text='Custom date for old sales', null=True),
        ),
    ]
