# Generated by Django 4.2.7 on 2026-02-19 16:48

from django.db import migrations, models
import multibliz_pos.storage


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, storage=multibliz_pos.storage.ProductImageStorage(), upload_to='products/'),
        ),
    ]
