# Generated by Django 5.2.7 on 2025-12-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('generation_interval_days', models.PositiveIntegerField(default=30)),
                ('auto_generate_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forecast Configuration',
                'verbose_name_plural': 'Forecast Configuration',
            },
        ),
    ]
